/**
 * HandoffPackage — requirement #39.
 * A self-contained brief that lets a *different* coding agent take over
 * (Codex → Claude → Cursor → Gemini) without reading the original chat history.
 */
import { HANDOFF_SECTIONS } from '../../domain/ai-schemas.js';
import { RUN_STATUS, BUILD_STATUS, GATE_RESULT } from '../../domain/constants.js';
import { nextActionToText } from './next-action.js';

export function buildHandoffPackage({
  project, metadata, git, stages, currentStage, tasks, criteria, specs, risks, regressions,
  gate, health, progress, memory, memoryStore, unit, integration, e2e, build, nextAction,
  prompts = [], agentSessions = [], doNotBreak = [],
} = {}) {
  const memoryText = memoryStore ? memoryStore.render(memory, { maxChars: 3500 }) : '(no project memory recorded)';
  const doneTasks = tasks.filter((t) => t.status === 'done');
  const openTasks = tasks.filter((t) => t.status !== 'done' && t.status !== 'cancelled');

  const testLines = [
    build ? `- Build: \`${build.command || 'n/a'}\` → ${build.status}${build.exitCode !== null && build.exitCode !== undefined ? ` (exit ${build.exitCode})` : ''}` : '- Build: not run',
    unit ? `- Unit (${unit.framework}): ${unit.passed}/${unit.total} ${unit.status}` : '- Unit: not run',
    integration ? `- Integration (${integration.framework}): ${integration.passed}/${integration.total} ${integration.status}` : '- Integration: not run',
    e2e ? `- E2E (${e2e.framework}): ${e2e.passed}/${e2e.total} ${e2e.status}` : '- E2E: not run',
  ];
  const failing = [];
  for (const run of [unit, integration, e2e]) {
    if (run && (run.status === RUN_STATUS.FAIL || run.status === RUN_STATUS.ERROR)) {
      for (const c of (run.cases || []).slice(0, 8)) failing.push(`- [${run.suite}] ${c.name}${c.file ? ` (${c.file})` : ''}`);
    }
  }

  const body = [
    `## Project Summary`,
    `**${project.name}** — ${project.description || 'no description recorded'}`,
    `Workspace: \`${project.workspacePath}\``,
    `Health: **${health ? health.status : 'unknown'}** · Status: ${project.status} · Progress: ${progress && progress.percent !== null ? `${progress.percent}%` : 'unknown'}`,
    ``,
    `## Architecture`,
    memoryText.includes('## Architecture')
      ? memoryText.split('## Architecture')[1].split('## ')[0].trim()
      : `- Language: ${(metadata && metadata.primaryLanguage) || 'unknown'}\n- Framework: ${(metadata && metadata.framework) || 'unknown'}\n- Frameworks: ${(((metadata && metadata.frameworks) || [])).join(', ') || 'none'}\n- Package manager: ${(metadata && metadata.packageManager) || 'unknown'}\n- Detailed architecture memory: ${memory ? `see Project Memory v${memory.version}` : 'not recorded yet'}`,
    ``,
    `## Current Stage`,
    currentStage ? `${currentStage.name} — ${currentStage.status}` : 'unknown',
    ...stages.map((s) => `- ${s.name}: ${s.status}`),
    ``,
    `## Completed Work`,
    doneTasks.length ? doneTasks.slice(0, 25).map((t) => `- ${t.title}`).join('\n') : '- nothing marked done yet',
    ``,
    `## Current Task`,
    nextAction ? nextAction.objective : '(none)',
    ``,
    `## Known Issues`,
    risks.filter((r) => r.status === 'open').length
      ? risks.filter((r) => r.status === 'open').slice(0, 20).map((r) => `- (${r.severity}) ${r.title}${r.suggested_action ? ` — ${r.suggested_action}` : ''}`).join('\n')
      : '- no open risks recorded',
    regressions.length ? `\nRegressions:\n${regressions.map((r) => `- (${r.severity}) ${r.title}`).join('\n')}` : '',
    ``,
    `## Relevant Files`,
    (nextAction && nextAction.relevantFiles && nextAction.relevantFiles.length)
      ? nextAction.relevantFiles.map((f) => `- ${f}`).join('\n')
      : '- (none identified — inspect the workspace)',
    ``,
    `## Tests`,
    ...testLines,
    failing.length ? `\nFailing cases:\n${failing.join('\n')}` : '',
    ``,
    `## Next Action`,
    nextAction ? nextActionToText(nextAction) : '(none)',
    ``,
    `## Constraints`,
    ...(doNotBreak.length ? doNotBreak : [
      'Do not delete, skip or weaken tests.',
      'Do not commit secrets or .env files.',
      'Do not touch unrelated files.',
    ]).map((c) => `- ${c}`),
    ``,
    `## Verification`,
    ...((nextAction && nextAction.verificationCommands) || ['npm run build', 'npm test']).map((c) => `- \`${c}\``),
    ``,
    `---`,
    `Generated by AI Project Commander at ${new Date().toISOString()}.`,
    `Open tasks: ${openTasks.length} · Acceptance criteria: ${criteria.length} · Gate: ${gate ? gate.result : GATE_RESULT.UNKNOWN}`,
    `Previous prompts recorded: ${prompts.length} · Imported agent sessions: ${agentSessions.length}`,
  ].filter((l) => l !== '' || true).join('\n');

  const present = HANDOFF_SECTIONS.filter((s) => body.includes(`## ${s}`));
  return {
    sections: present,
    missingSections: HANDOFF_SECTIONS.filter((s) => !present.includes(s)),
    markdown: body,
    generatedAt: new Date().toISOString(),
    targetAgents: ['codex', 'claude_code', 'cursor', 'gemini', 'generic_cli'],
  };
}

export function handoffFilename(project) {
  const slug = String(project.name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `handoff-${slug}-${Date.now()}.md`;
}

export { BUILD_STATUS };
