/** DOM helpers. Everything renders via textContent — no innerHTML with dynamic data (XSS-safe). */

export function h(tag, props = {}, children = []) {
  const el = document.createElement(tag);
  for (const [k, v] of Object.entries(props || {})) {
    if (v === undefined || v === null || v === false) continue;
    if (k === 'class') el.className = v;
    else if (k === 'text') el.textContent = String(v);
    else if (k === 'html') el.innerHTML = v; // only ever used with static, self-authored markup
    else if (k === 'dataset') Object.assign(el.dataset, v);
    else if (k === 'style' && typeof v === 'object') Object.assign(el.style, v);
    else if (k.startsWith('on') && typeof v === 'function') el.addEventListener(k.slice(2).toLowerCase(), v);
    else if (k === 'for') el.setAttribute('for', v);
    else el.setAttribute(k, v === true ? '' : String(v));
  }
  append(el, children);
  return el;
}

export function append(parent, children) {
  const list = Array.isArray(children) ? children : [children];
  for (const c of list) {
    if (c === null || c === undefined || c === false) continue;
    if (Array.isArray(c)) { append(parent, c); continue; }
    parent.appendChild(typeof c === 'string' || typeof c === 'number' ? document.createTextNode(String(c)) : c);
  }
  return parent;
}

export function clear(el) { while (el.firstChild) el.removeChild(el.firstChild); return el; }
export function frag(children) { return append(document.createDocumentFragment(), children); }

export const fmt = {
  date(ts) {
    if (!ts) return '—';
    const d = new Date(ts);
    if (Number.isNaN(d.getTime())) return String(ts);
    return d.toLocaleString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
  },
  time(ts) {
    if (!ts) return '—';
    const d = new Date(ts);
    if (Number.isNaN(d.getTime())) return String(ts);
    return d.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  },
  rel(ts) {
    if (!ts) return '—';
    const diff = Date.now() - new Date(ts).getTime();
    if (Number.isNaN(diff)) return '—';
    const s = Math.round(diff / 1000);
    if (s < 60) return `${s}s ago`;
    const m = Math.round(s / 60);
    if (m < 60) return `${m}m ago`;
    const hr = Math.round(m / 60);
    if (hr < 24) return `${hr}h ago`;
    const d = Math.round(hr / 24);
    return `${d}d ago`;
  },
  duration(ms) {
    if (ms === null || ms === undefined) return '—';
    if (ms < 1000) return `${Math.round(ms)}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    return `${Math.floor(ms / 60000)}m ${Math.round((ms % 60000) / 1000)}s`;
  },
  num(n) { return n === null || n === undefined ? '—' : Number(n).toLocaleString(); },
  bytes(b) {
    if (b === null || b === undefined) return '—';
    if (b < 1024) return `${b} B`;
    if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
    return `${(b / 1024 / 1024).toFixed(1)} MB`;
  },
  truncate(s, n = 160) {
    const str = String(s ?? '');
    return str.length > n ? `${str.slice(0, n - 1)}…` : str;
  },
};

const HEALTH_CLASS = { healthy: 'badge-healthy', warning: 'badge-warning', critical: 'badge-critical', unknown: 'badge-unknown' };
const STATUS_CLASS = {
  pass: 'badge-pass', fail: 'badge-fail', error: 'badge-fail', timeout: 'badge-warning',
  unsupported: 'badge-unsupported', unknown: 'badge-unknown', error_unparsed: 'badge-warning',
};

export function healthBadge(status) {
  return h('span', { class: `badge ${HEALTH_CLASS[status] || 'badge-unknown'}`, text: status || 'unknown' });
}

export function statusBadge(status) {
  return h('span', { class: `badge ${STATUS_CLASS[status] || 'badge-unknown'}`, text: status || 'unknown' });
}

export function gateBadge(gate) {
  if (!gate) return h('span', { class: 'badge badge-unknown', text: 'gate: n/a' });
  const cls = gate.result === 'PASS' ? 'badge-pass' : gate.result === 'BLOCKED' ? 'badge-critical' : gate.result === 'FAIL' ? 'badge-fail' : 'badge-unknown';
  return h('span', { class: `badge ${cls}`, text: `gate: ${gate.result}`, title: gate.explanation || '' });
}

export function mockBadge(provider) {
  if (!provider) return null;
  if (provider === 'mock') return h('span', { class: 'badge badge-mock', title: 'Generated by the deterministic Mock provider — not a real LLM', text: 'mock (deterministic)' });
  return h('span', { class: 'badge badge-info', text: provider });
}

export function metric(label, value, { foot = '', cls = '', sm = false } = {}) {
  return h('div', { class: `metric ${cls}` }, [
    h('div', { class: 'label', text: label }),
    h('div', { class: `value ${sm ? 'sm' : ''}`, text: value }),
    foot ? h('div', { class: 'foot', text: foot }) : null,
  ]);
}

export function card(title, body, { actions = [], hint = '', id = null } = {}) {
  return h('section', { class: 'card', id }, [
    title ? h('div', { class: 'card-head' }, [
      h('h2', { text: title }),
      h('div', { class: 'row' }, [hint ? h('span', { class: 'hint', text: hint }) : null, ...actions]),
    ]) : null,
    h('div', { class: 'card-pad' }, body),
  ]);
}

export function table(columns, rows, { empty = 'No rows.', rowKey = null, onRowClick = null } = {}) {
  if (!rows || !rows.length) return stateEmpty(empty);
  const thead = h('thead', {}, h('tr', {}, columns.map((c) => h('th', { class: c.num ? 'num' : '', style: c.width ? { width: c.width } : {}, text: c.label }))));
  const tbody = h('tbody', {}, rows.map((r, i) => h('tr', {
    dataset: rowKey ? { key: String(rowKey(r, i)) } : {},
    style: onRowClick ? { cursor: 'pointer' } : {},
    onClick: onRowClick ? () => onRowClick(r, i) : undefined,
  }, columns.map((c) => {
    const v = c.render ? c.render(r, i) : r[c.key];
    const td = h('td', { class: c.num ? 'num' : '' });
    append(td, v === null || v === undefined ? '—' : v);
    return td;
  }))));
  return h('div', { class: 'table-wrap' }, h('table', { class: 'tbl' }, [thead, tbody]));
}

export function stateLoading(label = 'Loading…') {
  return h('div', { class: 'stack-sm' }, [
    h('div', { class: 'small muted', text: label }),
    h('div', { class: 'skeleton', style: { width: '70%' } }),
    h('div', { class: 'skeleton', style: { width: '92%' } }),
    h('div', { class: 'skeleton', style: { width: '55%' } }),
  ]);
}

export function stateEmpty(title, detail = '') {
  return h('div', { class: 'state' }, [
    h('h3', { text: title }),
    detail ? h('div', { class: 'small', text: detail }) : null,
  ]);
}

export function stateError(err, onRetry = null) {
  return h('div', { class: 'state error' }, [
    h('h3', { text: err && err.message ? err.message : 'Something went wrong' }),
    err && err.hint ? h('div', { class: 'small', text: err.hint }) : null,
    err && err.code ? h('div', { class: 'evidence', text: `code: ${err.code}` }) : null,
    onRetry ? h('div', { style: { marginTop: '10px' } }, h('button', { class: 'btn btn-sm', text: 'Retry', onClick: onRetry })) : null,
  ]);
}

export function toast(message, kind = 'info', timeout = 5000) {
  const region = document.getElementById('toast-region');
  if (!region) return;
  const el = h('div', { class: `toast ${kind}`, text: message });
  region.appendChild(el);
  setTimeout(() => { try { region.removeChild(el); } catch { /* already removed */ } }, timeout);
}

export function modal(title, bodyContent, { onClose = null } = {}) {
  const backdrop = h('div', { class: 'modal-backdrop', role: 'dialog', 'aria-modal': 'true' });
  const close = () => { backdrop.remove(); document.removeEventListener('keydown', onKey); if (onClose) onClose(); };
  const onKey = (e) => { if (e.key === 'Escape') close(); };
  const box = h('div', { class: 'modal' }, [
    h('div', { class: 'modal-head' }, [
      h('strong', { text: title }),
      h('button', { class: 'btn btn-sm btn-ghost', text: 'Close', onClick: close, 'aria-label': 'Close dialog' }),
    ]),
    h('div', { class: 'modal-body' }, bodyContent),
  ]);
  backdrop.appendChild(box);
  backdrop.addEventListener('click', (e) => { if (e.target === backdrop) close(); });
  document.addEventListener('keydown', onKey);
  document.body.appendChild(backdrop);
  const focusable = box.querySelector('button, input, textarea, select, a[href]');
  if (focusable) focusable.focus();
  return { close, backdrop };
}

export function evidenceList(evidence) {
  const list = Array.isArray(evidence) ? evidence : [];
  if (!list.length) return h('span', { class: 'evidence', text: 'no evidence recorded' });
  return h('div', { class: 'tag-list' }, list.slice(0, 12).map((e) => h('span', { class: 'chip', title: e.note || '', text: `${e.type}: ${fmt.truncate(e.ref, 56)}` })));
}

export function progressBar(progress) {
  if (!progress || progress.percent === null || progress.percent === undefined) {
    return h('div', { class: 'small muted', text: `Progress unknown — ${progress && progress.reason ? progress.reason : 'insufficient data'}` });
  }
  const pct = Math.max(0, Math.min(100, progress.percent));
  return h('div', { class: 'stack-sm' }, [
    h('div', { class: 'row-between' }, [
      h('span', { class: 'small', text: `${pct}%` }),
      h('span', { class: 'small muted', text: progress.reason || '' }),
    ]),
    h('div', { class: 'progress-bar' }, h('span', { style: { width: `${pct}%` } })),
  ]);
}

export function copyButton(text, label = 'Copy') {  return h('button', {
    class: 'btn btn-sm',
    text: label,
    onClick: async () => {
      try {
        await navigator.clipboard.writeText(text);
        toast('Copied to clipboard', 'ok', 2000);
      } catch {
        // Clipboard API can be blocked; fall back to a selection prompt.
        const ta = document.createElement('textarea');
        ta.value = text;
        document.body.appendChild(ta);
        ta.select();
        try { document.execCommand('copy'); toast('Copied to clipboard', 'ok', 2000); } catch { toast('Copy failed — select the text manually', 'error'); }
        document.body.removeChild(ta);
      }
    },
  });
}

/**
 * Load data and render, always exposing loading / empty / success / error states
 * (requirement #51). `renderer` may return a node, or null after mutating the container.
 */
export async function mountAsync(container, loader, renderer, { loadingLabel = 'Loading…', onError = null } = {}) {
  clear(container);
  container.appendChild(stateLoading(loadingLabel));
  try {
    const data = await loader();
    clear(container);
    const node = await renderer(data);
    if (node) container.appendChild(node);
    return data;
  } catch (err) {
    clear(container);
    container.appendChild(stateError(err, onError || (() => mountAsync(container, loader, renderer, { loadingLabel, onError }))));
    return null;
  }
}
